import 'dotenv/config';
import mongoose from 'mongoose';
import { Category } from './models/Category.js';
import { Product } from './models/Product.js';
import { generateProductCode } from './utils/codeGenerator.js';

const CATEGORIES = [
  { name: 'Bracelets', codePrefix: 'BR' },
  { name: 'Necklaces', codePrefix: 'NK' },
  { name: 'Earrings',  codePrefix: 'ER' },
  { name: 'Rings',     codePrefix: 'RG' },
  { name: 'Anklets',   codePrefix: 'AN' },
  { name: 'Bangles',   codePrefix: 'BG' },
  { name: 'Charms',    codePrefix: 'CH' },
  { name: 'Cuffs',     codePrefix: 'CF' },
  { name: 'Chains',    codePrefix: 'CN' },
  { name: 'Sets',      codePrefix: 'ST' },
];

// Consistent placeholder image per slug. Replace with real Cloudinary URLs via admin panel.
const img = (slug) => `https://picsum.photos/seed/${slug}/800/800`;

const PRODUCTS = [
  // ── BRACELETS (25) ────────────────────────────────────────────────────────
  {
    name: 'Moonlit Cascade Bracelet',
    category: 'Bracelets',
    material: 'Gold Plated Brass',
    price: 799,
    description: 'Delicate gold-plated links catch the light with every movement, creating a cascading shimmer effect on the wrist. Inspired by moonlit water, this bracelet pairs effortlessly with both casual and formal outfits. Available in three metal tones to match your personal style.',
    images: [img('moonlit-cascade-bracelet')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Gold',      price: 799, images: [img('moonlit-cascade-gold')],      isDefault: true  },
      { color: 'Rose Gold', price: 849, images: [img('moonlit-cascade-rosegold')],  isDefault: false },
      { color: 'Silver',    price: 749, images: [img('moonlit-cascade-silver')],    isDefault: false },
    ],
  },
  {
    name: 'Twisted Vine Bracelet',
    category: 'Bracelets',
    material: 'Sterling Silver',
    price: 849,
    description: 'Handcrafted from polished sterling silver, this bracelet features an intricate twisted vine pattern that wraps gracefully around the wrist. The organic texture adds a nature-inspired elegance that complements everyday and special-occasion wear alike. Lightweight yet durable, it is a timeless addition to any jewellery collection.',
    images: [img('twisted-vine-bracelet'), img('twisted-vine-bracelet-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Frosted Petal Bracelet',
    category: 'Bracelets',
    material: 'Rose Gold Plated',
    price: 599,
    description: 'A soft rose gold finish gives this delicate petal-inspired bracelet a dreamy, feminine quality. Each petal link is individually crafted for a subtle dimensional effect that catches the eye. Perfect for gifting or wearing as a signature piece on any occasion.',
    images: [img('frosted-petal-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Bohemian Shell Bracelet',
    category: 'Bracelets',
    material: 'Copper',
    price: 449,
    description: 'Inspired by free-spirited coastal living, this copper bracelet features artisan-crafted shell motifs on a fine chain. The warm copper tones develop a beautiful patina over time, making it uniquely yours. Best styled with flowy silhouettes and summer separates.',
    images: [img('bohemian-shell-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Midnight Bead Bracelet',
    category: 'Bracelets',
    material: 'Oxidised Silver',
    price: 549,
    description: 'Tiny oxidised silver beads are strung in an alternating pattern to create a subtle textured effect on the wrist. The dark oxidised finish gives this bracelet an edgy, contemporary personality. Stack it with lighter metals for a bold contrast look.',
    images: [img('midnight-bead-bracelet')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Daisy Link Bracelet',
    category: 'Bracelets',
    material: 'Gold Plated Brass',
    price: 599,
    description: 'Cheerful daisy-shaped links in warm gold-plated brass make this bracelet a joyful everyday accessory. Each daisy is set with a tiny faceted centre that catches the light beautifully. A perfect gift for someone who loves nature-inspired jewellery.',
    images: [img('daisy-link-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Crystal Stream Bracelet',
    category: 'Bracelets',
    material: '925 Silver',
    price: 1299,
    description: 'Fine 925 silver links flow like a gentle stream, adorned with tiny crystal-cut elements that sparkle with every movement. The minimalist structure makes this bracelet versatile enough for work, brunch, or evening wear. Available in silver and rose gold finishes.',
    images: [img('crystal-stream-bracelet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Silver',    price: 1299, images: [img('crystal-stream-silver')],   isDefault: true  },
      { color: 'Rose Gold', price: 1349, images: [img('crystal-stream-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Layered Orbit Bracelet',
    category: 'Bracelets',
    material: 'Rose Gold Plated',
    price: 849,
    description: 'Three ultra-fine rose gold-plated chains orbit around the wrist in perfect harmony, creating a layered look without the effort. The adjustable lobster clasp ensures a comfortable fit on most wrist sizes. A go-to piece for effortless everyday elegance.',
    images: [img('layered-orbit-bracelet'), img('layered-orbit-bracelet-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Hammered Sun Bracelet',
    category: 'Bracelets',
    material: 'Copper',
    price: 699,
    description: 'Each hammered copper disc on this bracelet is finished by hand, creating a warm artisanal texture reminiscent of sun-baked earth. Copper\'s natural warmth complements all skin tones beautifully. This bracelet suits both ethnic ensembles and contemporary casual wear.',
    images: [img('hammered-sun-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Celestial Thread Bracelet',
    category: 'Bracelets',
    material: 'Gold Plated Brass',
    price: 749,
    description: 'Ultra-fine chains woven together like threads of starlight make this bracelet a delicate yet striking piece. The adjustable slide closure makes it easy to layer with other bracelets. Available in four colour tones to suit every mood and wardrobe.',
    images: [img('celestial-thread-bracelet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Gold',           price: 749, images: [img('celestial-thread-gold')],    isDefault: true  },
      { color: 'Rose Gold',      price: 799, images: [img('celestial-thread-rg')],      isDefault: false },
      { color: 'Oxidised Black', price: 849, images: [img('celestial-thread-black')],   isDefault: false },
      { color: 'Matte Silver',   price: 699, images: [img('celestial-thread-silver')],  isDefault: false },
    ],
  },
  {
    name: 'Minimalist Bar Bracelet',
    category: 'Bracelets',
    material: 'Sterling Silver',
    price: 999,
    description: 'A single polished sterling silver bar sits elegantly at the centre of this fine chain bracelet. The clean, graphic silhouette appeals to lovers of minimal jewellery who prefer understated luxury. It transitions seamlessly from desk to dinner.',
    images: [img('minimalist-bar-bracelet'), img('minimalist-bar-bracelet-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Filigree Garden Bracelet',
    category: 'Bracelets',
    material: 'Gold Plated Brass',
    price: 1499,
    description: 'Intricate gold-plated filigree panels joined by fine chain links create this garden-inspired statement piece. The delicate lacework of the filigree catches light from every angle. Perfect for weddings, receptions, and festive celebrations.',
    images: [img('filigree-garden-bracelet'), img('filigree-garden-bracelet-2')],
    inStock: true,
    featured: true,
  },
  {
    name: 'Stone Cascade Bracelet',
    category: 'Bracelets',
    material: 'Oxidised Silver',
    price: 949,
    description: 'Smooth semi-precious stone beads cascade along an oxidised chain for a rich, earthy look. The muted tones of the oxidised metal complement the natural stone perfectly. Available in three dark finishes to match different styling aesthetics.',
    images: [img('stone-cascade-bracelet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Oxidised Black', price: 949, images: [img('stone-cascade-black')],  isDefault: true  },
      { color: 'Antique Bronze', price: 999, images: [img('stone-cascade-bronze')], isDefault: false },
      { color: 'Gunmetal',       price: 899, images: [img('stone-cascade-gun')],    isDefault: false },
    ],
  },
  {
    name: 'Herringbone Link Bracelet',
    category: 'Bracelets',
    material: 'Stainless Steel',
    price: 749,
    description: 'A flat herringbone chain in polished stainless steel creates a fluid, ribbon-like bracelet that drapes beautifully on the wrist. Hypoallergenic and tarnish-resistant, this piece is built for confident everyday wear. The secure push-lock clasp keeps it comfortably in place all day.',
    images: [img('herringbone-link-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Petal Shower Bracelet',
    category: 'Bracelets',
    material: 'Rose Gold Plated',
    price: 649,
    description: 'Tiny rose gold-plated petals hang from a delicate chain like a gentle shower of blossoms. The movement and soft pink tones give this bracelet a romantic, feminine energy. Ideal for bridesmaid gifts, anniversaries, or a personal treat.',
    images: [img('petal-shower-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Anchor Chain Bracelet',
    category: 'Bracelets',
    material: 'Bronze',
    price: 499,
    description: 'A classic anchor chain in warm bronze tones gives this bracelet a nautical-meets-bohemian character. The simple design makes it endlessly stackable with other chain bracelets. A versatile everyday piece for the adventurous spirit.',
    images: [img('anchor-chain-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Vintage Lace Bracelet',
    category: 'Bracelets',
    material: 'White Gold Plated',
    price: 1899,
    description: 'White gold-plated links are intricately patterned to resemble vintage lace, creating a bracelet that feels both heirloom and contemporary. The lustrous finish glows warmly against the skin. Available in pearl white and champagne to suit your preference.',
    images: [img('vintage-lace-bracelet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Pearl White', price: 1899, images: [img('vintage-lace-pearl')],     isDefault: true  },
      { color: 'Champagne',   price: 1999, images: [img('vintage-lace-champagne')], isDefault: false },
    ],
  },
  {
    name: 'Butterfly Dance Bracelet',
    category: 'Bracelets',
    material: 'Gold Plated Brass',
    price: 799,
    description: 'Lightweight gold-plated brass butterflies flutter along a delicate chain, creating a playful, whimsical wrist accent. The three-dimensional butterfly charms catch the light with a gentle shimmer. A perfect summer accessory or meaningful gift for a loved one.',
    images: [img('butterfly-dance-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Waterfall Chain Bracelet',
    category: 'Bracelets',
    material: '925 Silver',
    price: 949,
    description: 'Multiple fine 925 silver chains cascade from a single bar, creating the impression of a miniature waterfall on the wrist. The layered effect is elegant without being heavy or bulky. A beautiful everyday piece for those who love fluid, feminine jewellery.',
    images: [img('waterfall-chain-bracelet')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Sunflower Bloom Bracelet',
    category: 'Bracelets',
    material: 'Copper',
    price: 449,
    description: 'Tiny hand-stamped sunflower motifs in warm copper alternate with smooth rounds along this delicate bracelet. The cheerful design brings a touch of sunshine to any outfit. Makes a sweet, affordable gift for birthdays and celebrations.',
    images: [img('sunflower-bloom-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Textured Stack Bracelet',
    category: 'Bracelets',
    material: 'Sterling Silver',
    price: 1099,
    description: 'A hammered and polished alternating texture on this sterling silver bracelet creates visual interest even as a standalone piece. Designed to be worn stacked or solo, it adapts to any styling preference. Available in silver, gold, and rose gold finishes.',
    images: [img('textured-stack-bracelet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Silver',    price: 1099, images: [img('textured-stack-silver')],   isDefault: true  },
      { color: 'Gold',      price: 1149, images: [img('textured-stack-gold')],     isDefault: false },
      { color: 'Rose Gold', price: 1149, images: [img('textured-stack-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Evil Eye Charm Bracelet',
    category: 'Bracelets',
    material: 'Gold Plated Brass',
    price: 699,
    description: 'A row of tiny evil eye charms in vivid enamel is set in warm gold-plated brass for a protective and stylish wrist accent. The symbolic design makes this bracelet a popular gift for loved ones. Pairs beautifully with other gold chain bracelets.',
    images: [img('evil-eye-charm-bracelet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Arabesque Link Bracelet',
    category: 'Bracelets',
    material: 'Oxidised Silver',
    price: 849,
    description: 'Arabesque-patterned oval links in oxidised silver give this bracelet an architectural, artisan quality. The interlocking geometric design draws inspiration from Mughal craft traditions. Available in oxidised black and antique bronze to suit different aesthetics.',
    images: [img('arabesque-link-bracelet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Oxidised Black', price: 849, images: [img('arabesque-black')],  isDefault: true  },
      { color: 'Antique Bronze', price: 899, images: [img('arabesque-bronze')], isDefault: false },
    ],
  },
  {
    name: 'Pearl Station Bracelet',
    category: 'Bracelets',
    material: 'White Gold Plated',
    price: 2599,
    description: 'Lustrous freshwater pearls are individually set at intervals along a white gold-plated fine chain for a refined, bridal-ready bracelet. The classic combination of pearls and precious metal feels both timeless and modern. Available in pearl white and champagne tones.',
    images: [img('pearl-station-bracelet'), img('pearl-station-bracelet-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Pearl White', price: 2599, images: [img('pearl-station-pearl')],     isDefault: true  },
      { color: 'Champagne',   price: 2699, images: [img('pearl-station-champagne')], isDefault: false },
    ],
  },
  {
    name: 'Geo Disc Bracelet',
    category: 'Bracelets',
    material: 'Stainless Steel',
    price: 899,
    description: 'Alternating hammered and smooth geometric discs in polished stainless steel create a clean, modern bracelet with subtle textural interest. Hypoallergenic and water-resistant, it is built for all-day everyday wear. Its balanced proportions make it suitable for both casual and professional looks.',
    images: [img('geo-disc-bracelet')],
    inStock: true,
    featured: false,
  },

  // ── NECKLACES (12) ────────────────────────────────────────────────────────
  {
    name: 'Crescent Moon Necklace',
    category: 'Necklaces',
    material: 'Sterling Silver',
    price: 1099,
    description: 'A finely detailed crescent moon pendant in sterling silver hangs from a delicate cable chain for a celestial, feminine look. The moon\'s surface is lightly hammered for a natural, handcrafted feel. Available in three metal tones to complement any wardrobe.',
    images: [img('crescent-moon-necklace'), img('crescent-moon-necklace-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Silver',    price: 1099, images: [img('crescent-moon-silver')],   isDefault: true  },
      { color: 'Gold',      price: 1149, images: [img('crescent-moon-gold')],     isDefault: false },
      { color: 'Rose Gold', price: 1099, images: [img('crescent-moon-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Layered Coin Necklace',
    category: 'Necklaces',
    material: 'Gold Plated Brass',
    price: 1249,
    description: 'Three hammered gold-plated brass coins of varying sizes are layered at different chain lengths for an effortlessly styled look. The warm coin finish suits both casual and festive dressing. Best worn with deep V-necks or open-collar shirts.',
    images: [img('layered-coin-necklace')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Rose Quartz Drop Necklace',
    category: 'Necklaces',
    material: '925 Silver',
    price: 1599,
    description: 'A faceted rose quartz stone is wire-wrapped in 925 silver and suspended from a fine chain for a soft, romantic pendant necklace. The gentle pink of the quartz complements the cool silver beautifully. Perfect for everyday wear or as a meaningful gift.',
    images: [img('rose-quartz-drop-necklace'), img('rose-quartz-drop-necklace-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Twisted Rope Necklace',
    category: 'Necklaces',
    material: 'Rose Gold Plated',
    price: 949,
    description: 'Multiple fine rose gold-plated chains are twisted together into a rope-like structure that creates a luxurious yet lightweight necklace. The soft twist catches light along its entire length. A classic piece that works beautifully with any neckline.',
    images: [img('twisted-rope-necklace')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Satellite Chain Necklace',
    category: 'Necklaces',
    material: 'Gold Plated Brass',
    price: 849,
    description: 'Tiny round beads punctuate a fine gold-plated brass chain at regular intervals, creating a modern satellite chain necklace with geometric precision. The subtle rhythm of bead and chain gives this necklace a contemporary minimalist appeal. Available in gold and rose gold.',
    images: [img('satellite-chain-necklace')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Gold',      price: 849, images: [img('satellite-chain-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 899, images: [img('satellite-chain-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Teardrop Crystal Necklace',
    category: 'Necklaces',
    material: 'Stainless Steel',
    price: 1149,
    description: 'A faceted crystal teardrop in clear glass is mounted in polished stainless steel hardware and suspended from a box chain. The pendant refracts light in every direction, creating a subtle rainbow effect indoors and outdoors. Available in three metal finishes for versatile pairing.',
    images: [img('teardrop-crystal-necklace'), img('teardrop-crystal-necklace-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Silver',   price: 1149, images: [img('teardrop-crystal-silver')],  isDefault: true  },
      { color: 'Gold',     price: 1199, images: [img('teardrop-crystal-gold')],    isDefault: false },
      { color: 'Gunmetal', price: 1099, images: [img('teardrop-crystal-gunmetal')],isDefault: false },
    ],
  },
  {
    name: 'Lotus Bloom Necklace',
    category: 'Necklaces',
    material: 'Oxidised Silver',
    price: 1349,
    description: 'An oxidised silver lotus pendant in full bloom hangs from a dark-toned rolo chain for a spiritually meaningful and visually striking necklace. The lotus symbolises purity and new beginnings, making it a thoughtful gift. The oxidised finish lends a vintage, artisan character.',
    images: [img('lotus-bloom-necklace')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Hammered Disc Necklace',
    category: 'Necklaces',
    material: 'Copper',
    price: 749,
    description: 'A wide, hammered copper disc is suspended from a fine chain, creating a statement pendant necklace with a raw, handcrafted aesthetic. The warm copper tones glow beautifully against both dark and light clothing. Ideal for those who love bold artisanal accessories.',
    images: [img('hammered-disc-necklace')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Star Cluster Choker',
    category: 'Necklaces',
    material: 'White Gold Plated',
    price: 2099,
    description: 'A constellation of tiny stars set in white gold-plated settings makes this choker a dazzling statement piece for evenings. The snug choker fit highlights the neckline beautifully. Available in three luminous finishes including pearl white and champagne.',
    images: [img('star-cluster-choker'), img('star-cluster-choker-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Pearl White',    price: 2099, images: [img('star-cluster-pearl')],   isDefault: true  },
      { color: 'Champagne',      price: 2199, images: [img('star-cluster-champ')],   isDefault: false },
      { color: 'Midnight Black', price: 1999, images: [img('star-cluster-black')],   isDefault: false },
    ],
  },
  {
    name: 'Geometric Triangle Necklace',
    category: 'Necklaces',
    material: 'Gold Plated Brass',
    price: 949,
    description: 'A bold equilateral triangle pendant in gold-plated brass makes a modern, architectural statement as a pendant necklace. The geometric form looks striking against both casual and formal backgrounds. Available in gold and rose gold finishes.',
    images: [img('geometric-triangle-necklace')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Gold',      price: 949, images: [img('geo-triangle-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 999, images: [img('geo-triangle-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Pearl Strand Necklace',
    category: 'Necklaces',
    material: 'Sterling Silver',
    price: 3099,
    description: 'A single strand of uniformly sized freshwater pearls with a sterling silver clasp creates a classic, understated necklace that transcends trends. The natural lustre of the pearls brings an elegant softness to any ensemble. A wardrobe essential for formal occasions.',
    images: [img('pearl-strand-necklace'), img('pearl-strand-necklace-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Dainty Cross Necklace',
    category: 'Necklaces',
    material: 'Rose Gold Plated',
    price: 799,
    description: 'A petite rose gold-plated cross pendant hangs from a fine chain, offering a simple and meaningful everyday necklace. The cross is lightly etched with a fine line border for added detail. A perfect gift for christenings, confirmations, or personal expression.',
    images: [img('dainty-cross-necklace')],
    inStock: true,
    featured: false,
  },

  // ── EARRINGS (10) ─────────────────────────────────────────────────────────
  {
    name: 'Cascading Teardrop Earrings',
    category: 'Earrings',
    material: 'Gold Plated Brass',
    price: 749,
    description: 'Gold-plated brass teardrop frames cascade in a tiered sequence, creating dramatic yet lightweight drop earrings. The open metalwork frames catch light beautifully with every turn of the head. Available in gold and rose gold finishes.',
    images: [img('cascading-teardrop-earrings'), img('cascading-teardrop-earrings-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Gold',      price: 749, images: [img('cascading-teardrop-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 799, images: [img('cascading-teardrop-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Twisted Hoop Earrings',
    category: 'Earrings',
    material: 'Sterling Silver',
    price: 949,
    description: 'Sterling silver wire is twisted and bent into smooth hoops with a subtle texture that catches the light. The medium size strikes the perfect balance between statement and everyday wearability. These hoops complement both casual and dressed-up looks effortlessly.',
    images: [img('twisted-hoop-earrings')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Lotus Petal Drops',
    category: 'Earrings',
    material: 'Rose Gold Plated',
    price: 849,
    description: 'Delicate rose gold-plated lotus petals are layered into lightweight drop earrings that sway gently with movement. The flower-shaped design brings a soft, feminine energy to any look. Available in rose gold, gold, and silver finishes.',
    images: [img('lotus-petal-drops')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Rose Gold', price: 849, images: [img('lotus-petal-rosegold')], isDefault: true  },
      { color: 'Gold',      price: 899, images: [img('lotus-petal-gold')],     isDefault: false },
      { color: 'Silver',    price: 799, images: [img('lotus-petal-silver')],   isDefault: false },
    ],
  },
  {
    name: 'Star Dangle Earrings',
    category: 'Earrings',
    material: 'Gold Plated Brass',
    price: 699,
    description: 'Five-pointed star charms in gold-plated brass dangle from fine hooks for a simple yet celestial earring. The polished star surface catches light beautifully against the ear. Perfect for everyday wear or casual occasions where you want a touch of sparkle.',
    images: [img('star-dangle-earrings')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Oxidised Jhumka Earrings',
    category: 'Earrings',
    material: 'Oxidised Silver',
    price: 599,
    description: 'Traditional jhumka bell earrings in oxidised silver feature intricate floral hand-engraved details on the dome and a fine bead fringe around the edge. The oxidised finish deepens the craftsmanship of each engraved detail. Available in three dark tone finishes.',
    images: [img('oxidised-jhumka-earrings'), img('oxidised-jhumka-earrings-2')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Oxidised Black', price: 599, images: [img('jhumka-black')],  isDefault: true  },
      { color: 'Antique Bronze', price: 649, images: [img('jhumka-bronze')], isDefault: false },
      { color: 'Gunmetal',       price: 649, images: [img('jhumka-gun')],    isDefault: false },
    ],
  },
  {
    name: 'Minimalist Bar Studs',
    category: 'Earrings',
    material: '925 Silver',
    price: 549,
    description: 'Slim, polished 925 silver bars are set flush against the ear for a clean, modern stud earring. The simple form complements without competing with any outfit. An essential everyday jewellery piece for the minimalist wardrobe.',
    images: [img('minimalist-bar-studs')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Chandelier Drop Earrings',
    category: 'Earrings',
    material: 'White Gold Plated',
    price: 1699,
    description: 'Multi-tier white gold-plated chandelier earrings cascade with fine chain and crystal detail for a glamorous evening look. The lightweight construction means comfortable wear even through long occasions. Best suited for formal events, weddings, and celebrations.',
    images: [img('chandelier-drop-earrings'), img('chandelier-drop-earrings-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Hammered Circle Earrings',
    category: 'Earrings',
    material: 'Copper',
    price: 499,
    description: 'Wide copper circles with a hand-hammered surface texture create bold, artisanal hoop earrings with a raw beauty. The warm copper colour complements earth-toned clothing beautifully. A statement piece that pairs well with both bohemian and contemporary styles.',
    images: [img('hammered-circle-earrings')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Pearl Halo Drops',
    category: 'Earrings',
    material: 'Gold Plated Brass',
    price: 949,
    description: 'A central freshwater pearl is framed by a halo of fine gold-plated chain for a unique twist on the classic pearl earring. The floating chain halo creates movement and a soft shimmer around the pearl. Available in gold and rose gold finishes.',
    images: [img('pearl-halo-drops')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Gold',      price: 949, images: [img('pearl-halo-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 999, images: [img('pearl-halo-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Triangle Geo Earrings',
    category: 'Earrings',
    material: 'Stainless Steel',
    price: 649,
    description: 'Polished stainless steel triangles with a flat, geometric profile make for clean, architectural earrings suitable for minimalist aesthetics. Hypoallergenic and lightweight, they are comfortable for all-day wear. The simple form pairs with virtually any outfit.',
    images: [img('triangle-geo-earrings')],
    inStock: true,
    featured: false,
  },

  // ── RINGS (10) ────────────────────────────────────────────────────────────
  {
    name: 'Celestial Signet Ring',
    category: 'Rings',
    material: 'Sterling Silver',
    price: 1349,
    description: 'A flat signet ring face in sterling silver features a hand-engraved celestial map motif, making each piece unique. The substantial face and delicate shank balance boldness with elegance. Available in four metal tones to suit all preferences.',
    images: [img('celestial-signet-ring'), img('celestial-signet-ring-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Silver',         price: 1349, images: [img('signet-silver')],  isDefault: true  },
      { color: 'Gold',           price: 1399, images: [img('signet-gold')],    isDefault: false },
      { color: 'Rose Gold',      price: 1399, images: [img('signet-rg')],      isDefault: false },
      { color: 'Oxidised Black', price: 1299, images: [img('signet-black')],   isDefault: false },
    ],
  },
  {
    name: 'Twisted Band Ring',
    category: 'Rings',
    material: 'Gold Plated Brass',
    price: 849,
    description: 'Two strands of gold-plated brass are twisted together into a single band ring that creates a visually interesting continuous texture. The twisted structure gives this simple band an artisan quality. Comfortable to wear on any finger for any occasion.',
    images: [img('twisted-band-ring')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Floral Filigree Ring',
    category: 'Rings',
    material: 'Rose Gold Plated',
    price: 1049,
    description: 'An intricate filigree flower sits atop a fine rose gold-plated band for a dainty, feminine statement ring. The lacework of the filigree creates a sense of delicacy and skilled craftsmanship. Available in rose gold and gold finishes.',
    images: [img('floral-filigree-ring')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Rose Gold', price: 1049, images: [img('filigree-ring-rg')],   isDefault: true  },
      { color: 'Gold',      price: 1099, images: [img('filigree-ring-gold')], isDefault: false },
    ],
  },
  {
    name: 'Hammered Knuckle Ring',
    category: 'Rings',
    material: 'Oxidised Silver',
    price: 749,
    description: 'A wide, flat oxidised silver band with a hammered surface is designed to sit at the first knuckle as a bold statement piece. The raw, textured finish gives this ring an edgy, contemporary character. Best worn alone or with minimal other rings.',
    images: [img('hammered-knuckle-ring')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Stacked Midi Ring Set',
    category: 'Rings',
    material: '925 Silver',
    price: 1599,
    description: 'Three ultra-fine 925 silver bands of varying widths are designed to be stacked together for a curated, layered ring look. Each band has a subtly different finish — polished, hammered, and twisted — for visual variety. Available in silver and rose gold finishes.',
    images: [img('stacked-midi-ring-set'), img('stacked-midi-ring-set-2')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Silver',    price: 1599, images: [img('midi-ring-silver')],   isDefault: true  },
      { color: 'Rose Gold', price: 1649, images: [img('midi-ring-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Geometric Statement Ring',
    category: 'Rings',
    material: 'Stainless Steel',
    price: 899,
    description: 'A faceted geometric form in polished stainless steel makes this ring a bold conversation piece. The multi-faceted surface reflects light dramatically from every angle. Hypoallergenic and tarnish-resistant for confident everyday wear.',
    images: [img('geometric-statement-ring')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Vine Leaf Ring',
    category: 'Rings',
    material: 'Gold Plated Brass',
    price: 799,
    description: 'Delicate vine leaves wrap around the shank of this gold-plated brass ring in a continuous botanical pattern. The fine detail of each leaf gives this ring a handcrafted, artisan quality. An ideal gift for nature lovers and botanical jewellery enthusiasts.',
    images: [img('vine-leaf-ring')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Pearl Dome Ring',
    category: 'Rings',
    material: 'White Gold Plated',
    price: 1899,
    description: 'A dome-shaped cluster of tiny pearls set in white gold-plated prongs creates a feminine, vintage-inspired cocktail ring. The soft lustre of the pearls contrasts beautifully with the bright metal setting. A perfect ring for formal occasions and evening wear.',
    images: [img('pearl-dome-ring')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Open Arc Ring',
    category: 'Rings',
    material: 'Copper',
    price: 649,
    description: 'A smooth copper arc band is bent into an open shape that wraps around the finger without closing, making it adjustable for most sizes. The warm copper tone develops a unique patina with wear. A casual, artisanal ring for everyday minimalist styling.',
    images: [img('open-arc-ring')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Crescent Moon Ring',
    category: 'Rings',
    material: 'Sterling Silver',
    price: 949,
    description: 'A fine crescent moon form in sterling silver sits at a slight angle on the finger for a modern, celestial look. The curved shape of the moon feels elegant and comfortable to wear through the day. Available in silver, gold, and rose gold finishes.',
    images: [img('crescent-moon-ring')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Silver',    price: 949, images: [img('moon-ring-silver')],   isDefault: true  },
      { color: 'Gold',      price: 999, images: [img('moon-ring-gold')],     isDefault: false },
      { color: 'Rose Gold', price: 999, images: [img('moon-ring-rosegold')], isDefault: false },
    ],
  },

  // ── ANKLETS (8) ───────────────────────────────────────────────────────────
  {
    name: 'Coastal Charm Anklet',
    category: 'Anklets',
    material: 'Gold Plated Brass',
    price: 549,
    description: 'Tiny shell, starfish, and anchor charms in gold-plated brass hang from a fine anklet chain for a beach-inspired look. The layered charms create a gentle tinkling sound with movement. Available in gold and rose gold finishes.',
    images: [img('coastal-charm-anklet'), img('coastal-charm-anklet-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Gold',      price: 549, images: [img('coastal-anklet-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 599, images: [img('coastal-anklet-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Delicate Bead Anklet',
    category: 'Anklets',
    material: 'Sterling Silver',
    price: 699,
    description: 'Tiny sterling silver beads alternate with fine chain links to create a textured, minimalist anklet. The simple design is elegant without being overstated. A perfect everyday anklet for those who prefer understated accessories.',
    images: [img('delicate-bead-anklet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Shell Drop Anklet',
    category: 'Anklets',
    material: 'Rose Gold Plated',
    price: 599,
    description: 'Natural shell drops are strung on a fine rose gold-plated chain for a light, natural anklet with a coastal feel. The organic shell shapes vary slightly in colour, making each piece unique. Best styled with sandals and breezy summer looks.',
    images: [img('shell-drop-anklet')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Twisted Bell Anklet',
    category: 'Anklets',
    material: 'Oxidised Silver',
    price: 499,
    description: 'Small oxidised silver bells are suspended from twisted chain links to create an anklet with a soft, musical jingle. The traditional bell motif is rendered in a contemporary matte finish. A festive and meaningful everyday accessory.',
    images: [img('twisted-bell-anklet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Layered Coin Anklet',
    category: 'Anklets',
    material: 'Gold Plated Brass',
    price: 449,
    description: 'Three tiny hammered gold-plated brass coins hang at intervals from a fine anklet chain for a boho-chic look. The coin motif references ancient jewellery traditions in a modern, lightweight form. Best paired with bare feet or strappy sandals.',
    images: [img('layered-coin-anklet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Hammered Disc Anklet',
    category: 'Anklets',
    material: '925 Silver',
    price: 749,
    description: 'Small hand-hammered discs in 925 silver are linked together to create a chain-style anklet with a tactile, artisan quality. The hammered texture catches light beautifully with every step. Available in silver and gold finishes.',
    images: [img('hammered-disc-anklet')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Silver', price: 749, images: [img('disc-anklet-silver')], isDefault: true  },
      { color: 'Gold',   price: 799, images: [img('disc-anklet-gold')],   isDefault: false },
    ],
  },
  {
    name: 'Feather Drop Anklet',
    category: 'Anklets',
    material: 'Bronze',
    price: 499,
    description: 'Tiny bronze feather charms are suspended from a fine chain anklet, creating a lightweight, bohemian accessory that sways with movement. The feather charms evoke a free-spirited energy perfect for summer. Ideal for festival styling and casual outdoor looks.',
    images: [img('feather-drop-anklet')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Crystal Ball Anklet',
    category: 'Anklets',
    material: 'White Gold Plated',
    price: 849,
    description: 'Tiny faceted crystal balls in white gold-plated settings are strung at intervals on a fine anklet chain for a subtle sparkle at the ankle. The delicate glimmer makes this anklet suitable for both day and evening wear. A refined choice for those who love understated glamour.',
    images: [img('crystal-ball-anklet')],
    inStock: true,
    featured: false,
  },

  // ── BANGLES (8) ───────────────────────────────────────────────────────────
  {
    name: 'Engraved Vine Bangle',
    category: 'Bangles',
    material: 'Gold Plated Brass',
    price: 1099,
    description: 'A smooth gold-plated brass bangle is hand-engraved with a continuous vine and leaf pattern for a refined, nature-inspired piece. The matte background of the engraving contrasts with the polished metal for beautiful definition. Available in gold and rose gold finishes.',
    images: [img('engraved-vine-bangle'), img('engraved-vine-bangle-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Gold',      price: 1099, images: [img('vine-bangle-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 1149, images: [img('vine-bangle-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Hammered Stack Bangle',
    category: 'Bangles',
    material: 'Sterling Silver',
    price: 899,
    description: 'A lightweight sterling silver bangle with an all-over hammered texture is designed for stacking two, three, or more together. The hammered surface catches light in multiple directions, creating a dynamic shimmer effect. A versatile bangle that works with casual and formal looks.',
    images: [img('hammered-stack-bangle')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Twisted Wire Bangle',
    category: 'Bangles',
    material: 'Copper',
    price: 599,
    description: 'Two strands of copper wire are twisted together and shaped into a rigid bangle with a handcrafted, artisanal quality. The warm copper tones develop a natural patina with wear. An affordable yet beautifully crafted everyday bangle.',
    images: [img('twisted-wire-bangle')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Enamel Bloom Bangle',
    category: 'Bangles',
    material: 'Gold Plated Brass',
    price: 1249,
    description: 'Rich botanical enamel inlay on a gold-plated brass bangle creates a vibrant, decorative piece inspired by garden florals. The smooth enamel surface and polished metal border create a refined, eye-catching contrast. A beautiful bangle for festive occasions and ethnic looks.',
    images: [img('enamel-bloom-bangle')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Oxidised Peacock Bangle',
    category: 'Bangles',
    material: 'Oxidised Silver',
    price: 849,
    description: 'An oxidised silver bangle featuring a hand-carved peacock in full-feather display makes for a bold, culturally rich jewellery piece. The dark oxidised finish deepens the detail of the carving dramatically. A statement bangle ideal for traditional Indian attire.',
    images: [img('oxidised-peacock-bangle')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Thin Midi Bangle',
    category: 'Bangles',
    material: '925 Silver',
    price: 749,
    description: 'An ultra-slim 925 silver bangle designed to be worn in multiples, stacked high for a modern, curated look. The smooth polished surface reflects light cleanly. Available in silver, gold, and rose gold finishes.',
    images: [img('thin-midi-bangle')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Silver',    price: 749, images: [img('midi-bangle-silver')],   isDefault: true  },
      { color: 'Gold',      price: 799, images: [img('midi-bangle-gold')],     isDefault: false },
      { color: 'Rose Gold', price: 799, images: [img('midi-bangle-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Stone Set Bangle',
    category: 'Bangles',
    material: 'Rose Gold Plated',
    price: 1599,
    description: 'A row of smooth cabochon stones set in a continuous bezel on a rose gold-plated bangle creates a feminine, luxurious look. The stones are flush-set for a sleek, uninterrupted profile. A sophisticated piece for formal occasions and evening wear.',
    images: [img('stone-set-bangle')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Ethnic Kadas Bangle',
    category: 'Bangles',
    material: 'Bronze',
    price: 699,
    description: 'A wide bronze kadas-style bangle features traditional tribal motifs stamped and repousse-finished for deep textural contrast. The substantial form and warm bronze tone give it an authentic, artisanal character. Best worn as a single statement piece with ethnic ensembles.',
    images: [img('ethnic-kadas-bangle')],
    inStock: true,
    featured: false,
  },

  // ── CHARMS (7) ────────────────────────────────────────────────────────────
  {
    name: 'Celestial Moth Charm',
    category: 'Charms',
    material: 'Gold Plated Brass',
    price: 349,
    description: 'A delicately detailed moth charm in gold-plated brass captures the mystical beauty of this nocturnal creature. The textured wings have an almost lacework quality that makes this charm exceptionally detailed at a small scale. Available in three metal tones.',
    images: [img('celestial-moth-charm')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Gold',      price: 349, images: [img('moth-charm-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 369, images: [img('moth-charm-rosegold')], isDefault: false },
      { color: 'Silver',    price: 329, images: [img('moth-charm-silver')],   isDefault: false },
    ],
  },
  {
    name: 'Butterfly Enamel Charm',
    category: 'Charms',
    material: 'Sterling Silver',
    price: 379,
    description: 'A hand-painted enamel butterfly in pastel tones is mounted on a sterling silver charm base with fine engraved antennae. The vibrant enamel colours make this charm stand out beautifully on any chain. A cheerful addition to any charm collection.',
    images: [img('butterfly-enamel-charm')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Heart Lock Charm',
    category: 'Charms',
    material: 'Rose Gold Plated',
    price: 429,
    description: 'A sculptural heart-shaped padlock in rose gold-plated brass comes with a tiny key charm, making it a meaningful symbol of connection. The weight and detail of the lock give it a luxurious feel despite its small size. Available in rose gold and gold finishes.',
    images: [img('heart-lock-charm')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Rose Gold', price: 429, images: [img('heart-lock-rg')],   isDefault: true  },
      { color: 'Gold',      price: 449, images: [img('heart-lock-gold')], isDefault: false },
    ],
  },
  {
    name: 'Evil Eye Drop Charm',
    category: 'Charms',
    material: 'Gold Plated Brass',
    price: 329,
    description: 'A hand-painted evil eye in vivid blue enamel is set in a gold-plated brass teardrop frame for a protective and stylish charm. The traditional symbolic form is rendered in a contemporary, polished style. Stack with other charms or wear alone for its meaning.',
    images: [img('evil-eye-drop-charm')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Lotus Bud Charm',
    category: 'Charms',
    material: 'Oxidised Silver',
    price: 429,
    description: 'An oxidised silver lotus bud charm captures the flower in its closed, pre-bloom state as a symbol of potential and purity. The detailed petal definition in oxidised metal has a beautiful craftsmanship quality. A meaningful charm for spiritual jewellery lovers.',
    images: [img('lotus-bud-charm')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Star Burst Charm',
    category: 'Charms',
    material: 'Stainless Steel',
    price: 319,
    description: 'A stainless steel starburst charm with radiating points captures the explosive energy of a star in a wearable form. The polished metal surface makes it shine even at its small size. Hypoallergenic and durable for everyday charm bracelet wear.',
    images: [img('star-burst-charm')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Clover Leaf Charm',
    category: 'Charms',
    material: 'Gold Plated Brass',
    price: 369,
    description: 'A four-leaf clover charm in gold-plated brass is finished with a light texture on each leaf for dimension and detail. The classic lucky symbol makes this an ideal gift charm for someone special. Pairs well with other nature-inspired charms on any chain.',
    images: [img('clover-leaf-charm')],
    inStock: true,
    featured: false,
  },

  // ── CUFFS (7) ─────────────────────────────────────────────────────────────
  {
    name: 'Desert Bloom Cuff',
    category: 'Cuffs',
    material: 'Copper',
    price: 1349,
    description: 'Inspired by desert flora, this open copper cuff features hand-stamped botanical motifs that wrap around the wide band. The warm copper develops a rich patina that deepens the look over time. Available in copper and antique bronze finishes.',
    images: [img('desert-bloom-cuff'), img('desert-bloom-cuff-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Copper',         price: 1349, images: [img('desert-cuff-copper')], isDefault: true  },
      { color: 'Antique Bronze', price: 1399, images: [img('desert-cuff-bronze')], isDefault: false },
    ],
  },
  {
    name: 'Hammered Wide Cuff',
    category: 'Cuffs',
    material: 'Sterling Silver',
    price: 1849,
    description: 'A substantial sterling silver cuff with an all-over deep hammered texture makes a bold yet elegant wrist statement. The open back allows for a comfortable, adjustable fit on most wrist sizes. The raw hammered surface catches light beautifully from every angle.',
    images: [img('hammered-wide-cuff')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Filigree Open Cuff',
    category: 'Cuffs',
    material: 'Gold Plated Brass',
    price: 1549,
    description: 'An open cuff in gold-plated brass is adorned with an intricate filigree arch that creates a delicate, luxurious look. The lacework filigree sits above the smooth cuff body for a beautiful structural contrast. A showstopping piece for festive occasions and bridal styling.',
    images: [img('filigree-open-cuff'), img('filigree-open-cuff-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Oxidised Tribal Cuff',
    category: 'Cuffs',
    material: 'Oxidised Silver',
    price: 1049,
    description: 'Bold tribal geometric motifs are hand-carved and oxidised on a wide silver cuff for a dramatic, statement piece. The oxidised finish makes every carved detail sharper and more visually pronounced. Best worn as a solo piece with minimal other jewellery.',
    images: [img('oxidised-tribal-cuff')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Geo Flat Cuff',
    category: 'Cuffs',
    material: 'Stainless Steel',
    price: 1149,
    description: 'A flat, geometric profile in polished stainless steel gives this open cuff a modern, architectural quality. The clean lines and smooth surface make it a versatile statement piece for contemporary wardrobes. Hypoallergenic and built for long-lasting wear.',
    images: [img('geo-flat-cuff')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Twisted Wire Cuff',
    category: 'Cuffs',
    material: 'Bronze',
    price: 899,
    description: 'Multiple bronze wires are twisted together and formed into a rigid open cuff with a sculptural, handcrafted quality. The multi-strand twist creates a rich, complex texture along the wrist. A bold piece that suits bohemian and artisan jewellery aesthetics perfectly.',
    images: [img('twisted-wire-cuff')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Crystal Set Cuff',
    category: 'Cuffs',
    material: 'White Gold Plated',
    price: 2599,
    description: 'A wide white gold-plated open cuff features a continuous channel of sparkling crystal stones set across its face. The all-around crystal coverage creates a dazzling, red-carpet worthy piece for special occasions. Available in pearl white, champagne, and midnight black settings.',
    images: [img('crystal-set-cuff'), img('crystal-set-cuff-2')],
    inStock: true,
    featured: false,
    variants: [
      { color: 'Pearl White',    price: 2599, images: [img('crystal-cuff-pearl')], isDefault: true  },
      { color: 'Champagne',      price: 2699, images: [img('crystal-cuff-champ')], isDefault: false },
      { color: 'Midnight Black', price: 2499, images: [img('crystal-cuff-black')], isDefault: false },
    ],
  },

  // ── CHAINS (7) ────────────────────────────────────────────────────────────
  {
    name: 'Figaro Link Chain',
    category: 'Chains',
    material: 'Gold Plated Brass',
    price: 1349,
    description: 'A classic figaro pattern in gold-plated brass — three small round links followed by one elongated oval — creates an enduringly stylish chain necklace. The pattern has been a jewellery staple for decades for very good reason. Available in gold and rose gold finishes.',
    images: [img('figaro-link-chain'), img('figaro-link-chain-2')],
    inStock: true,
    featured: true,
    variants: [
      { color: 'Gold',      price: 1349, images: [img('figaro-chain-gold')],     isDefault: true  },
      { color: 'Rose Gold', price: 1399, images: [img('figaro-chain-rosegold')], isDefault: false },
    ],
  },
  {
    name: 'Rope Twist Chain',
    category: 'Chains',
    material: 'Sterling Silver',
    price: 1549,
    description: 'Multiple sterling silver strands are twisted into a continuous rope chain that has both visual and tactile richness. The twisted structure catches light from every angle, creating a brilliant shimmer along the neckline. A timeless chain suitable for wearing alone or layering with pendants.',
    images: [img('rope-twist-chain')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Box Link Chain',
    category: 'Chains',
    material: 'Rose Gold Plated',
    price: 1049,
    description: 'Perfectly square box links in rose gold-plated brass connect seamlessly for a smooth, uniform chain with a modern profile. The flat, mirrored surfaces of each link reflect light cleanly and consistently. A versatile chain suitable for everyday layering or pendant wear.',
    images: [img('box-link-chain')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Herringbone Flat Chain',
    category: 'Chains',
    material: 'Gold Plated Brass',
    price: 1749,
    description: 'A classic herringbone pattern in gold-plated brass creates a flat, ribbon-like chain that drapes with elegant fluidity on the neckline. The seamless V-shaped link pattern is a hallmark of refined chain design. A sophisticated necklace that looks beautiful at any length.',
    images: [img('herringbone-flat-chain'), img('herringbone-flat-chain-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Curb Link Chain',
    category: 'Chains',
    material: 'Stainless Steel',
    price: 1149,
    description: 'Uniform flattened curb links in polished stainless steel create a bold, chunky chain with a modern street-luxe appeal. Hypoallergenic and tarnish-resistant for confident daily wear through any conditions. Pairs equally well with casual streetwear and formal looks.',
    images: [img('curb-link-chain')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Singapore Twist Chain',
    category: 'Chains',
    material: '925 Silver',
    price: 1449,
    description: 'The Singapore chain pattern in 925 silver features twisted oval links with a distinctive spiral texture that creates a beautiful sparkling effect. This classic chain style suits both pendant wear and solo statement styling. Lightweight yet substantial in its appearance.',
    images: [img('singapore-twist-chain')],
    inStock: false,
    featured: false,
  },
  {
    name: 'Ball Drop Chain',
    category: 'Chains',
    material: 'Oxidised Silver',
    price: 849,
    description: 'Uniform polished ball links in oxidised silver create a simple yet striking chain necklace with a graphic, modern character. The dark oxidised finish gives the rounded balls an almost sculptural quality. An elegant everyday chain for those who prefer darker metal tones.',
    images: [img('ball-drop-chain')],
    inStock: true,
    featured: false,
  },

  // ── SETS (6) ──────────────────────────────────────────────────────────────
  {
    name: 'Celestial Moon Set',
    category: 'Sets',
    material: 'Gold Plated Brass',
    price: 2599,
    description: 'A co-ordinated necklace, earrings, and bracelet set in gold-plated brass, all featuring the same crescent moon and star motif for a unified celestial look. Each piece is individually finished to the same high standard for a seamless matching ensemble. Perfect for gifting or a personal festive treat.',
    images: [img('celestial-moon-set'), img('celestial-moon-set-2')],
    inStock: true,
    featured: true,
  },
  {
    name: 'Delicate Daisy Set',
    category: 'Sets',
    material: '925 Silver',
    price: 2099,
    description: 'A matching necklace and earrings set in 925 silver featuring petite daisy flower motifs on fine chain. The uniform floral detailing across both pieces creates a coherent, fresh jewellery story. Ideal for everyday wear from spring through summer.',
    images: [img('delicate-daisy-set')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Boho Layered Set',
    category: 'Sets',
    material: 'Rose Gold Plated',
    price: 2399,
    description: 'A multi-piece boho set in rose gold-plated brass includes a layered pendant necklace, hoop earrings, and a stacking bracelet in matching tones and motifs. The cohesive rose gold palette across all three pieces creates an effortlessly styled look. Perfect for the free-spirited jewellery lover.',
    images: [img('boho-layered-set'), img('boho-layered-set-2')],
    inStock: true,
    featured: true,
  },
  {
    name: 'Oxidised Temple Set',
    category: 'Sets',
    material: 'Oxidised Silver',
    price: 1849,
    description: 'A temple-inspired jewellery set in oxidised silver includes a wide collar necklace, drop earrings, and a charm bracelet with matching deity and floral motifs. The deep oxidised finish enhances the intricacy of each hand-carved detail. A rich, culturally inspired set for festive and traditional occasions.',
    images: [img('oxidised-temple-set')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Pearl Elegance Set',
    category: 'Sets',
    material: 'White Gold Plated',
    price: 3599,
    description: 'A three-piece pearl jewellery set in white gold-plated metal includes a pearl-drop pendant necklace, pearl stud earrings, and a pearl station bracelet. The uniformity of the pearl selection and metal tone creates a polished, bridal-ready ensemble. A luxurious gift for weddings and other special occasions.',
    images: [img('pearl-elegance-set'), img('pearl-elegance-set-2')],
    inStock: true,
    featured: false,
  },
  {
    name: 'Geometric Minimal Set',
    category: 'Sets',
    material: 'Stainless Steel',
    price: 2099,
    description: 'A co-ordinated necklace and earrings set in polished stainless steel featuring clean geometric forms in matching proportions. The hypoallergenic metal and minimal design make this set suitable for everyday wear even for those with sensitive skin. A modern, versatile jewellery set for the contemporary wardrobe.',
    images: [img('geometric-minimal-set')],
    inStock: true,
    featured: false,
  },
];

// ── Run ───────────────────────────────────────────────────────────────────────
await mongoose.connect(process.env.MONGODB_URI);
console.log('Connected to MongoDB');

await Product.deleteMany({});
await Category.deleteMany({});
console.log('Wiped all existing products and categories');

await Category.insertMany(CATEGORIES);
console.log(`Created ${CATEGORIES.length} categories`);

let created = 0;
for (const p of PRODUCTS) {
  const productCode = await generateProductCode(p.category);
  await Product.create({ ...p, productCode });
  created++;
  process.stdout.write(`\r  Inserting products... ${created}/${PRODUCTS.length}`);
}

console.log(`\nCreated ${created} products`);
await mongoose.disconnect();
console.log(`\nSeed complete — ${CATEGORIES.length} categories, ${created} products.`);
